//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSObject<OS_xpc_object>;

__attribute__((visibility("hidden")))
@interface _CSStoreXPCRepresentation : NSObject <NSSecureCoding>
{
    NSObject<OS_xpc_object> *_XPCRepresentation;
}

+ (_Bool)supportsSecureCoding;
+ (id)classesForXPCInterface;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (const struct __CSStore *)createCSStoreWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithCSStore:(struct __CSStore *)arg1;

@end

