//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MobileCoreServices/_LSSharedWebCredentialsAppLinkPlugIn.h>

__attribute__((visibility("hidden")))
@interface _LSHandoffCompatibilityAppLinkPlugIn : _LSSharedWebCredentialsAppLinkPlugIn
{
}

- (void)getAppLinkWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)init;

@end

