//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface LSBundleRecordUpdater : NSObject
{
    struct LSContext _context;
    _Bool _hasContext;
    unsigned int _bundleID;
    struct LSBundleData _bundleData;
    NSString *_bundleIdentifier;
}

@property(readonly, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (int)updateBundleRecord;
- (void)parseSINFDictionary:(id)arg1;
- (void)parseiTunesMetadata:(id)arg1;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1;

@end

