//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (LSCachedValuesAdditions)
- (_Bool)_LS_BoolForKey:(id)arg1;
- (id)_LS_safeObjectForKey:(id)arg1 ofType:(Class)arg2;
@end

